name: Laravel CI/CD

on:
  push:
    branches:
      - main  # Branche principale où vous poussez le code

jobs:
  build:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Choisissez la version de PHP que vous utilisez
        extensions: mbstring, bcmath, zip  # Liste des extensions PHP requises pour Laravel

    - name: Install dependencies
      run: |
        composer install --no-dev --optimize-autoloader


    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} robinson@185.98.137.99 << 'EOF'
          cd /var/www/TP_API_MBA1
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force  # Assurez-vous que les migrations sont appliquées
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart php-fpm  # Redémarre PHP-FPM pour appliquer les changements
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
