name: Deploy Laravel API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test SSH Connection
      env:
        REMOTE_HOST: ${{ secrets.VPS_IP }}
        REMOTE_USER: ${{ secrets.VPS_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "echo 'SSH connection successful'"

    - name: Deploy to Server
      env:
        REMOTE_HOST: ${{ secrets.VPS_IP }}
        REMOTE_USER: ${{ secrets.VPS_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << EOF
          cd /var/www/TP_API_MBA1
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan storage:link
          sudo systemctl reload nginx
        EOF

    - name: Verify Laravel Worker Status
      env:
        REMOTE_HOST: ${{ secrets.VPS_IP }}
        REMOTE_USER: ${{ secrets.VPS_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "sudo systemctl is-active --quiet laravel-worker && echo 'Laravel worker is active' || echo 'Laravel worker is NOT active'"

    - name: Check Application Health
      env:
        APP_URL: ${{ secrets.APP_URL }}
      run: |
        curl -s -o /dev/null -w "%{http_code}" $APP_URL | grep -q "200" && echo "Application is healthy" || echo "Application is NOT healthy"
